export const PRODUCETYPES = [
  { id: 1, name: "Broilers", category: "Livestock" },
  { id: 2, name: "Eggs", category: "Livestock" },
  { id: 3, name: "Beef - Buffalo & Cattle", category: "Livestock" },
  { id: 4, name: "Goat & Sheep", category: "Livestock" },
  { id: 5, name: "Day Old Chicks", category: "Livestock" },
  { id: 6, name: "Fertilized Eggs", category: "Livestock" },
  { id: 7, name: "Miscellaneous Livestock", category: "Livestock" },
  { id: 8, name: "Vegetables", category: "Crops" },
  { id: 9, name: "Fruits", category: "Crops" },
  { id: 10, name: "Paddy", category: "Crops" },
  { id: 11, name: "Miscellaneous Crops", category: "Crops" },
  { id: 12, name: "Ornamental Plants", category: "Crops" },
  { id: 13, name: "Cut Flowers", category: "Crops" },
];
